### ISSUE TITLE
Does not run in macOS (Python 3.6) - Problems with PNG images

### ISSUE THREAD

**Issue by victordomingos** [morten1982/crossviper#1]
It seems that, at least in some platforms, tkinter does not take PNG images. The last time I had to use an image file in tkinter, i had to convert it to GIF first.

```
$ python3 /Users/victor/Downloads/crossviper-master/crossviper.py 
Traceback (most recent call last):
  File "/Users/victor/Downloads/crossviper-master/crossviper.py", line 1691, in <module>
    app = CrossViper(master=None)
  File "/Users/victor/Downloads/crossviper-master/crossviper.py", line 1562, in __init__
    self.initUI()
  File "/Users/victor/Downloads/crossviper-master/crossviper.py", line 1658, in initUI
    self.rightPanel = RightPanel(self.panedWindow)
  File "/Users/victor/Downloads/crossviper-master/crossviper.py", line 658, in __init__
    self.initUI()
  File "/Users/victor/Downloads/crossviper-master/crossviper.py", line 718, in initUI
    newIcon = tk.PhotoImage(file=self.dir + 'images/new.png')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 3539, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 3495, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "/Users/victor/Downloads/crossviper-master/images/new.png"
```

This kind of issue seems to have been explained here:
https://stackoverflow.com/questions/27599311/tkinter-photoimage-doesnt-not-support-png-image

**Comment by morten1982** [comment]
Do you use tkinter 8.6 ? 
I thought tkinter 8.6 does know how to manage with .png .... tkinter 8.5 doesn't

**Comment by victordomingos** [comment]
In mac OS X, the officially recommended Tcl/Tk version for Python 3.6 is ActiveTcl 8.5.18.0. This page clearly states that 8.6 is not supported in this platform, so 8.6 currently is not cross-platform.

https://www.python.org/download/mac/tcltk/
